### PR TITLE
WIP: Copy tests from ebrakke/python-redux

### PR DESCRIPTION
**Pull request by kasbah**
I copied the tests over from [python-redux](https://github.com/ebrakke/python-redux). These are writen for Python 3.4 so can be run with:

```
python3 -m unittest discover
```

As of now, they error with: 

```
ImportError: cannot import name 'bind_action_creators'
```

I guess this is not implemented. Would love some insight into this and whether it is viable to copy these tests over.

### CODE REVIEW

**Comment by kasbah** [comment]
Ok, I removed the `bind_action_creators` test and made some tweaks and these run now. Still getting 12 failures/errors but those seem a bit harder to figure out. 

```
Ran 40 tests in 0.019s

FAILED (failures=9, errors=3)
```

**Comment by kasbah** [comment]
Looks like the initial problems are since the [tests expect use of `logging`](https://github.com/usrlocalben/pydux/pull/7/files#diff-7a0c70dae0ba25909dc1625a15701662R166). How do you want to approach this? Should we add logging or handle this in a different way?

**Comment by usrlocalben** [comment]
I checked out your branch and started on it locally.

I removed the tests that were spying on the logger and fixed a few bugs and translation inconsistencies.

```~/pydux % python -m unittest discover
....................................
----------------------------------------------------------------------
Ran 36 tests in 0.011s

OK
```

Unless you have an objection, I'll start with your branch, add a few commits from what I have here, and then merge to master.

**Comment by kasbah** [comment]
Sounds great!

**Comment by kasbah** [comment]
Is 0.2.0 going to go up on PyPI soon?

**Comment by usrlocalben** [comment]
pypi is now at 0.2.0

**Pull request merged**
